server:
  # 端口设置
  port: 8082
  servlet:
    context-path: /

# Spring配置
spring:
  profiles: prod
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://8.134.33.6:3306/anonymous_letter?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 连接数据库的账号
    username: root
    # 连接数据库的密码
    password: 452454zhjZHJ#
  redis:
    host: 8.134.33.6
    port: 6379
    # redis密码，默认为空
    password:
  # 开启热部署
  devtools:
    restart:
      enabled: true


# 日志配置
logging:
  # 日志输出级别
  level:
    ROOT: info

# 自评报告
upload:
  img:
    path: /photo/


# swagger配置
springfox:
  documentation:
    swagger:
      v2:
        host: 8.134.33.6
        enabled: true
# Swagger
# swagger:
  # host
  #host: 120.24.160.104:40000
#  enable: true
#    swagger-ui:
#      base-url: http://8.134.33.6:8081/swagger-ui/index.html#

#swagger:
#  # host
#  host: 8.134.33.6:40000
#  enable: true

